name: flutter_actioncable
description: Actioncable adapter for flutter
version: 0.0.1
homepage: "https://github.com/jonorozcoc"

environment:
  sdk: ">=2.16.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  async: ">=2.8.2 <2.9.0"
  web_socket_channel: ">=2.1.0 <2.2.0"

dev_dependencies:
  flutter_test:
    sdk: flutter
  dart_code_metrics: 4.15.2
  flutter_lints: 1.0.4

flutter:
